apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp2-deployment
  labels:
    app: cp2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cp2-deployment
  template:
    metadata:
      labels:
        app: cp2-deployment
    spec:
      containers:
      - name: cp2-deployment
        image: arun1818/cp2
        ports:
        - containerPort: 80
